### ISSUE TITLE
Repo rename recommended

### ISSUE THREAD

**Issue by allanchen2019** [CJYKK/CJYKK.github.io#1]
PDXKK is better

**Comment by CJYKK** [comment]
Oh I don't think so.

**Comment by allanchen2019** [comment]
A good name boosts 150% performance gain at least, just like RGB LED equipped peripherals.

**Comment by CJYKK** [comment]
But I think it was not a good name.

**Comment by CJYKK** [comment]
Ok, I'm sorry.
PDXKK is better now.
